[build]
  command = "yarn build"
  publish = "out"
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# SPA rule. Always redirect any request to our index.html
[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200